projects:
    resource: "@ProjectsBundle/Controller/"
    type:     annotation
    prefix:   /api

staff:
    resource: "@StaffBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation
