oauth:
    resource: "@OauthBundle/Controller/"
    type:     annotation
    prefix:   /

staff:
    resource: "@StaffBundle/Controller/"
    type:     annotation
    prefix:   /api/staff

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"