analytics:
    resource: "@AnalyticsBundle/Controller/"
    type:     annotation
    prefix:   /api/analytics

technologies:
    resource: "@TechnologiesBundle/Controller/"
    type:     annotation
    prefix:   /api

projects:
    resource: "@ProjectsBundle/Controller/"
    type:     annotation
    prefix:   /api

staff:
    resource: "@StaffBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /doc

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc