services:
    linkedin.manager:
        class: LinkedinBundle\Services\Linkedin\Manager
        arguments:
            - "%linkedin_api_key%"
            - "%linkedin_secret_key%"
            - "%linkedin_calback_url%"
